### PR TITLE
add smart_dterm_smoothing and witchcraft

### PR DESCRIPTION
**Pull request by nerdCopter**
branched from commmit d901ea1ab

added smart_dterm_smoothing and witchcraft to filters tab for msp1.44 && 0.2.35+

maybe needs rebase from #86, #88 ?

### CODE REVIEW

**Comment by gretel** [comment]
yes, please rebase. https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

**Comment by gretel** [comment]
@nerdCopter tried cherrypicking 0bedd425e72284968803592487d5e94267a5017a on #88 and seems to works besides some layout issue:

image

**Comment by nerdCopter** [comment]
i can look into fixing.  i guess it was a personal choice due to initially being 4 columns (+gyroAvg) and needing it to fit somewhere.  below the others made sense at the time, but no longer.

**Comment by nerdCopter** [comment]
closing. 
 better, but with css/style issue. will continue to fix.

**Pull request closed without merging**
