### PR TITLE
[skip ci] rename Default presets to Default-0.2.0-RC1

### PR DESCRIPTION
**Pull request by nerdCopter**

### CODE REVIEW

**Comment by nerdCopter** [comment]
because defaults have changed on newer firmware.

**Comment by gretel** [comment]
> because defaults have changed on newer firmware.

sure but why this exact string? what is it refering to?

**Comment by nerdCopter** [comment]
so the last firware release was `0.2.0-RC1`.  when we release another firmware we can have matching `Defaults-0.x.y` for it

**Comment by gretel** [comment]
hu?

**Pull request closed without merging**
