### PR TITLE
configurator msp 1.49

### PR DESCRIPTION
**Pull request by nerdCopter**
* Works in conjunction with https://github.com/emuflight/EmuFlight/pull/352 .
* Assumes https://github.com/emuflight/EmuFlight/pull/348 will merge for sharpness 0 (off), if not, this will need modification.

### CODE REVIEW

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/msp/MSPHelper.js  2
- src/js/tabs/pid_tuning.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6128908&bid=20046904)

**Comment by nerdCopter** [comment]
&

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/msp/MSPHelper.js  2
- src/js/tabs/pid_tuning.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6128908&bid=20046904)

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/msp/MSPHelper.js  2
- src/js/tabs/pid_tuning.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6128908&bid=20046904)

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/msp/MSPHelper.js  2
- src/js/tabs/pid_tuning.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6128908&bid=20046904)

**Review by Kaiowarez — APPROVED** [review]

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/msp/MSPHelper.js  2
- src/js/tabs/pid_tuning.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6128908&bid=20046904)

**Pull request merged**
