### PR TITLE
better font handling

### PR DESCRIPTION
**Pull request by nerdCopter**
* v1 fonts resourced from butterflight fonts to match old firmware
* font versioning and handling allows for adding additional v2 fonts rather easily
* v1 fonts will be limited to the original quantity of butterflight based fonts
* OSD tab still has some wrong GPS and miscellaneous symbols for v1 fonts due to the nature of the source-code
* tested on 0.2.0 and 0.2.46

### CODE REVIEW

**Comment by nerdCopter** [comment]
v1: 



v2:

**Comment by gretel** [comment]
was flying `kaio` font today like it

**Comment by nerdCopter** [comment]
Travis' OSX deployment failing.

**Comment by gretel** [comment]
ya i noticed so what

**Pull request merged**
