### PR TITLE
integrated iforce2d.net mixercalc

### PR DESCRIPTION
**Pull request by nerdCopter**
* used/modified with permission from @iforce2d
* needs deep testing
* fixed constraints bug that is in original website/code
* limited to `mmix` only commands
* modified for embedding into EmuConfigurator
* modified presets
* replaced motors with propellers (with color variations of EmuFlight blue)
* modified constraints colors
* added key `r` input for prop-reversal
* added reverse-all-props button
* added copy-to-clipboard button
* added `set yaw_motors_reversed = OFF` and `save` to commands output.
* added/modified verbiage
* added focus highlighting for canvas and input box
* may need code cleanup

### CODE REVIEW

**Comment by nerdCopter** [comment]
These Codacy complaints are stupid

**Comment by nerdCopter** [comment]
looks like i introduced  a bug somehow, hovering mouse of green command area will display old calculations.

**Comment by nerdCopter** [comment]
* disabled the hover over and associated verbiage in order to reduce confusion

**Review by Quick-Flash — APPROVED** [review]
can't wait to see future improvements based on this.

**Pull request merged**
