### PR TITLE
add "deployment" to github release page

### PR DESCRIPTION
**Pull request by gretel**
this helps keeps semantics right. basically it works like this:

 * **work** on a branch (one feature/bugfix/whatever per branch **please**)
 * when done **commit and push** (`git commit -a && git push origin`)
   * submit a **pull request** (to `master`), check on the status checks (travis, codacy)
 * **wait** for feedback and approval
   * **tag** branch with version identifier to release (`git tag 0.28.4`)
   * **push with tags** (`git push --tags`)
 * if required update PR with changes
   * **re-tag** (`git tag -d 0.28.4; git push origin :0.28.4; git tag 0.28.4`)
   * **push** to add to PR (`git push --tags`) and change release (same tag will be overwritten/files get appended)

**both github releases and bintray will only get submitted when tagged**. bintray has been overflowing too many times!

besides, a **changelog** gets created which contains the commit logs since the last build.

please read on https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History to keep the commit logs tidy.

### CODE REVIEW

**Comment by nerdCopter** [comment]
do we bump version number for each "feature/bugfix/whatever" branch?

**Comment by gretel** [comment]
personally i would but traditionally this is done manually when people feel like it.

**Comment by nerdCopter** [comment]
@Quick-Flash please approve

**Comment by gretel** [comment]
@nerdCopter guess you have to review :)

**Comment by nerdCopter** [comment]
How are we supposed to tag for deployment to Bintray, yet not create a pre-release?

**Comment by gretel** [comment]
please read. like whats written above your question. thank you very much.

**Comment by gretel** [comment]
and please stop just silently demanding me to work so you can enjoy whatever that is. thanks again.

**Comment by nerdCopter** [comment]
no demands intended, thank you very kindly

**Comment by gretel** [comment]
* pull `master` in a state containing the merges (closed PRs) you want
 *create new branch `bump_version_whatever`
 * adjust metadata (`package.json` and stuff)
 * tag (as the intended release version) like `0.911.112` and push with tags

this should result in deployments happening. but nothing is going to be public on github. just like in the initial comment on the PR you did approve :P

**Pull request merged**
