### PR TITLE
add SFHSS to protocol list

### PR DESCRIPTION
**Pull request by nerdCopter**
* untested as i have no FC/protocol access

### CODE REVIEW

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/tabs/configuration.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6185366&bid=20186349)

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/tabs/configuration.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6185366&bid=20186349)

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/tabs/configuration.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6185366&bid=20186349)

**Review by Kaiowarez — APPROVED** [review]

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/js/tabs/configuration.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=6185366&bid=20186349)

**Pull request merged**
